version: '3'
services:
  web:
    build: site
    container_name: apache-finelia
    ports :
     - "8080:80"
    volumes:
     - ./:/var/www/html/
    depends_on:
     - database

  database:
    image: mysql:5.7
    container_name: mysql-finelia
    ports :
      - "3307:3306"
    environment:
      MYSQL_DATABASE: finelia
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-finelia
    depends_on:
      - database
    ports:
      - 8889:80
    environment:
        - PMA_ARBITRARY=1

      
      